{
 "title": "My-Metrics-Dashboard",
 "description": "CPU, Memory of Fronted, Backend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frontend CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=~\".*frontend.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\".*frontend.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=~\".*backend.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\".*backend.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}