name: TODO app deploy to EKS
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: 799227077423.dkr.ecr.ap-southeast-1.amazonaws.com
  FRONTEND_REPOSITORY: todo-app-frontend
  BACKEND_REPOSITORY: todo-app-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.28.2' # default is latest stable
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        mask-aws-account-id: false

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR Frontend
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: $FRONTEND_REPOSITORY
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./frontend
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Build, tag, and push docker image to Amazon ECR Backend
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: $BACKEND_REPOSITORY
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./backend
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --region ap-southeast-1 --name devops-test-cluster
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f eks.yaml